### PR TITLE
E2e test improvements

### PR DESCRIPTION
**Pull request by maurolacy**
Noticed some issues with the BTCStaking tests failing from time to time:
https://app.circleci.com/pipelines/github/babylonchain/babylon/1891/workflows/5e99488b-f864-45ad-856b-a01540cacb0c.

Turns out this is (likely / probably) a wasmer bug, with a [workaround](https://github.com/wasmerio/wasmer/issues/1568#issuecomment-1868697116) that was reported some time ago by Injective.

Changed the babylon docker image to use Debian bookworm instead of Alpine Linux. Seems to be working ~~(though not in CI)~~.

Also, did some syntax fixes, and robustness improvements of BTC Staking checks.

### CODE REVIEW

**Comment by SebastianElvis** [comment]
No objection on replacing alpine images with Debian ones, except for a minor concern on the image size. Our `ibcsim-wasmd` [image](https://github.com/babylonchain/babylon-deployment/blob/18ed2ff4102942c414117185fd27e33aeeec6491/contrib/images/ibcsim-wasmd/Dockerfile) and `bitcoindsim` [image](https://github.com/babylonchain/babylon-deployment/blob/7774da7cc22f0fdf413cd58f99f757d085b303fa/contrib/images/bitcoindsim/Dockerfile) are using Debian for some reason, and the resulting image size is pretty big (~2GB IIRC). What will be the size of Babylon image in this case?

**Comment by maurolacy** [comment]
> No objection on replacing alpine images with Debian ones, except for a minor concern on the image size. Our `ibcsim-wasmd` [image](https://github.com/babylonchain/babylon-deployment/blob/18ed2ff4102942c414117185fd27e33aeeec6491/contrib/images/ibcsim-wasmd/Dockerfile) and `bitcoindsim` [image](https://github.com/babylonchain/babylon-deployment/blob/7774da7cc22f0fdf413cd58f99f757d085b303fa/contrib/images/bitcoindsim/Dockerfile) are using Debian for some reason, and the resulting image size is pretty big (~2GB IIRC). What will be the size of Babylon image in this case?

~230MB. Will take a look at those images. Splitting the build stage from the run stage usually results in much smaller images.

**Review by SebastianElvis — APPROVED** [review]
Lgtm then!

**Comment by KonradStaniec** [comment]
I do not have strong opinions on image, although I slightly prefer alpine due to low image footprint.

How likely this is this wasmer bug ? From what I see in logs: https://app.circleci.com/pipelines/github/babylonchain/babylon/1891/workflows/5e99488b-f864-45ad-856b-a01540cacb0c, there are some logs about rly failure:
```
        2:06PM ERR failure when running app err="code id is required: invalid request"
        Error: code id is required: invalid request
```

and then this test fails `TestBTCTimestampingPhase2RlyTestSuite` 

And rest of the test most probably fail due to this test failing as there are some errors like:
`Received unexpected error:container already exists`

**Comment by maurolacy** [comment]
> I do not have strong opinions on image, although I slightly prefer alpine due to low image footprint.
> How likely this is this wasmer bug ? From what I see in logs: https://app.circleci.com/pipelines/github/babylonchain/babylon/1891/workflows/5e99488b-f864-45ad-856b-a01540cacb0c, there are some logs about rly failure:
> ```
>         2:06PM ERR failure when running app err="code id is required: invalid request"
>         Error: code id is required: invalid request
> ```
> 
> and then this test fails `TestBTCTimestampingPhase2RlyTestSuite`
> And rest of the test most probably fail due to this test failing as there are some errors like: `Received unexpected error:container already exists`

Hmm, I think I referenced the wrong CI log. Let me check.

**Comment by maurolacy** [comment]
Was pretty sure I saw this in the CI logs, yesterday monring, but I cannot find it. Perhaps I was just confused, and saw it locally. In any case, I saved part of the error to a file for reference. Here it is:

```
SIGABRT: abort
PC=0x31cd14c m=15 sigcode=18446744073709551610
signal arrived during cgo execution

goroutine 634 [syscall]:
runtime.cgocall(0x28bbe64, 0x400578ae68)
	runtime/cgocall.go:157 +0x44 fp=0x400578ae30 sp=0x400578adf0 pc=0x44d684
github.com/CosmWasm/wasmvm/internal/api._C2func_save_wasm(0xffff5aed7ce0, {0x0, 0x4006286000, 0x2ab24}, 0x0, 0x40063a4ea0)
	_cgo_gotypes.go:662 +0x40 fp=0x400578ae60 sp=0x400578ae30 pc=0x19c98a0
github.com/CosmWasm/wasmvm/internal/api.StoreCode.func1({0x33feb20?}, {0x40?, 0x4006286000?, 0x2397434?}, 0x0?)
	github.com/CosmWasm/wasmvm@v1.5.2/internal/api/lib.go:65 +0x84 fp=0x400578af00 sp=0x400578ae60 pc=0x19cc194
github.com/CosmWasm/wasmvm/internal/api.StoreCode({0x1?}, {0x4006286000?, 0x0?, 0x14?})
	github.com/CosmWasm/wasmvm@v1.5.2/internal/api/lib.go:65 +0xe4 fp=0x400578afd0 sp=0x400578af00 pc=0x19cc004
github.com/CosmWasm/wasmvm.(*VM).StoreCode(0x4005902000?, {0x4006286000?, 0x399c65b?, 0xc8000?})
	github.com/CosmWasm/wasmvm@v1.5.2/lib.go:60 +0x24 fp=0x400578b000 sp=0x400578afd0 pc=0x19d5e94
github.com/CosmWasm/wasmd/x/wasm/keeper.Keeper.create({{0x4220940, 0x400138a498}, {0x429f428, 0x4001ba3750}, {0x4238890, 0x4001518500}, {0x4221620, 0x40019c7fa0}, {0x42205e0, 0x40006ac9d8}, ...}, ...)
	github.com/CosmWasm/wasmd@v0.50.0/x/wasm/keeper/keeper.go:172 +0x454 fp=0x400578c6d0 sp=0x400578b000 pc=0x23974d4
github.com/CosmWasm/wasmd/x/wasm/keeper.msgServer.StoreCode({0x374d060?}, {0x425e7e0, 0x4006cd6e10}, 0x400710e6c0)
	github.com/CosmWasm/wasmd@v0.50.0/x/wasm/keeper/msg_server.go:37 +0x140 fp=0x400578ca30 sp=0x400578c6d0 pc=0x23a7fe0
github.com/CosmWasm/wasmd/x/wasm/keeper.(*msgServer).StoreCode(0x358?, {0x425e7e0?, 0x4006cd6e10?}, 0x3953360?)
	<autogenerated>:1 +0x34 fp=0x400578ca60 sp=0x400578ca30 pc=0x23c4ad4
github.com/CosmWasm/wasmd/x/wasm/types._Msg_StoreCode_Handler.func1({0x425e7e0, 0x4006cd6e10}, {0x3870400?, 0x400710e6c0})
	github.com/CosmWasm/wasmd@v0.50.0/x/wasm/types/tx.pb.go:2210 +0x74 fp=0x400578caa0 sp=0x400578ca60 pc=0x1a8b054
github.com/cosmos/cosmos-sdk/baseapp.(*MsgServiceRouter).registerMsgServiceHandler.func2.1({0x425da40, 0x4004e77180}, {0x400578cb48?, 0x1325720?}, 0x358?, 0x40061d1cc8)
```

I'll continue looking in the CI logs, and post a reference here if I find it.

**Comment by maurolacy** [comment]
The referenced log above is correct, by the way. Only incomplete. If you see the first error

```
    containers.go:130: 
        stderr:
    containers.go:131: Error: code id is required: invalid request
        2:06PM ERR failure when running app err="code id is required: invalid request"
```

it means the `store` procedure failed (and the node crashed), that's why the code id is zero. If you then could inspect the container logs, you'll see an error similar to the one I copied above.

I suppose that after I saw this in the CI, I reproduced it locally and copied the container error, obtained from doing `docker logs bbn-test-a-node-babylon-default-a-1` or similar.

**Pull request merged**
