### PR TITLE
u/relayer versions

### PR DESCRIPTION
**Pull request by maurolacy**
Updating relayer versions to a version tag, and finally enabling BTC timestamping phase 2 e2e test with the Hermes relayer.

### CODE REVIEW

**Comment by maurolacy** [comment]
> Hmm e2e seems timed out, and the reason seems to be that the docker image is not available?

Works on my local. And the docker tag is there: https://hub.docker.com/layers/informalsystems/hermes/v1.8.2/images/sha256-df0d1cf47f7026b8649e2e2c7366a63cc1c88cde0585dd8d458555b0be26bceb

Maybe a CI issue / timeout. Will re-retry once more.

**Comment by SebastianElvis** [comment]
> > Hmm e2e seems timed out, and the reason seems to be that the docker image is not available?
> 
> Works on my local. And the docker tag is there: [hub.docker.com/layers/informalsystems/hermes/v1.8.2/images/sha256-df0d1cf47f7026b8649e2e2c7366a63cc1c88cde0585dd8d458555b0be26bceb](https://hub.docker.com/layers/informalsystems/hermes/v1.8.2/images/sha256-df0d1cf47f7026b8649e2e2c7366a63cc1c88cde0585dd8d458555b0be26bceb)
> 
> Maybe a CI issue / timeout. Will re-retry once more.

My main suspect is the Cosmos relayer referenced [here](https://github.com/babylonchain/babylon/pull/568/files#diff-2910cd04aa90f54226c0dc71956cc1ee0dc68a78bd0a1cc2942af5f83d77dcebR17-R19). IIRC this image was pushed by @filippos47  and I'm not sure the this new version is available at AWS

**Comment by maurolacy** [comment]
> > > Hmm e2e seems timed out, and the reason seems to be that the docker image is not available?
> > 
> > 
> > Works on my local. And the docker tag is there: [hub.docker.com/layers/informalsystems/hermes/v1.8.2/images/sha256-df0d1cf47f7026b8649e2e2c7366a63cc1c88cde0585dd8d458555b0be26bceb](https://hub.docker.com/layers/informalsystems/hermes/v1.8.2/images/sha256-df0d1cf47f7026b8649e2e2c7366a63cc1c88cde0585dd8d458555b0be26bceb)
> > Maybe a CI issue / timeout. Will re-retry once more.
> 
> My main suspect is the Cosmos relayer referenced [here](https://github.com/babylonchain/babylon/pull/568/files#diff-2910cd04aa90f54226c0dc71956cc1ee0dc68a78bd0a1cc2942af5f83d77dcebR17-R19). IIRC this image was pushed by @filippos47 and I'm not sure the this new version is available at AWS

But that tag didn't change. Those tests are already working, AFAIK.

**Review by SebastianElvis — APPROVED** [review]
Nice!

**Pull request merged**
